include ../Makefile.tests_common

DRIVER ?= sht31
BOARD ?= octa

USEMODULE += sht31
USEMODULE += shell
USEMODULE += saul_default
USEMODULE += shell_commands
USEMODULE += ps 

include $(RIOTBASE)/Makefile.include